### ISSUE TITLE
See live routes at /phoenix/routes

### ISSUE THREAD

**Issue by danielberkompas** [phoenixframework/phoenix_live_reload#10]
This page would display the same output as `mix phoenix.routes`, but would automatically refresh whenever you change your router. It could look similar to the page Rails displays when it returns a 404 in development mode:

![action_controller__exception_caught](https://cloud.githubusercontent.com/assets/1186992/7442875/a1e76732-f0d8-11e4-8e40-1a740709b227.png)

New routes could be highlighted when the page refreshes. Inspiration: http://phoenixroutes.herokuapp.com/

**Comment by josevalim** [comment]
Actually, I also like the idea of showing this when a route is not found. However, if we are adding that, it needs to be added to Phoenix. :P And I am not sure how we could integrate live reload. We can do it by parts though.

**Comment by josevalim** [comment]
I believe Phoenix v1.4 is adding this to its exception pages.
