### ISSUE TITLE
New release that includes PR #96

### ISSUE THREAD

**Issue by axelson** [phoenixframework/phoenix_live_reload#101]
Hi, is it possible to get a new release that includes PR #96? I have a project that requires multiple live reload declarations.

From the commit list I initially thought it was included: https://github.com/phoenixframework/phoenix_live_reload/commits/master
But in the v1.2.1 tag and on hex.pm it is not included: https://github.com/phoenixframework/phoenix_live_reload/commits/v1.2.1

**Comment by josevalim** [comment]
Done!

**Comment by axelson** [comment]
Great, thanks!
