### ISSUE TITLE
Allow adding custom attributes to iframe

### ISSUE THREAD

**Issue by hauleth** [phoenixframework/phoenix_live_reload#104]
This would be useful for situations when there is used dynamic reload tooling like Turbolinks used as it would prevent needless updates of iframe.

**Comment by josevalim** [comment]
Sure, PR is welcome! I think we already have an app env for config. But it may be able to go to the plug too.

**Comment by hauleth** [comment]
#102 was the base for that. I created that issue for me, but I cannot assign myself to it.

**Comment by mbramson** [comment]
Confirming this would be useful to be able to add a nonce to the iframe to satisfy a content security policy.

**Comment by josevalim** [comment]
Are you sure a nonce is necessary? The iFrame is hosted in the same app and the contents of the iFrame are applied to the policy returned by the iFrame. If your CSP plugs comes after the live reload one, you should be good.
