### ISSUE TITLE
Can't find chan method

### ISSUE THREAD

**Issue by ruanwz** [phoenixframework/phoenix_live_reload#11]
The below code give an error: socket.chan is not a function

https://github.com/phoenixframework/phoenix_live_reload/blob/master/priv/static/phoenix_live_reload.js#L33

Should I upgrade phoenix to the latest one? I am currently using 0.12.0

**Comment by josevalim** [comment]
@ruanwz so you are on this weird spot between Phoenix releases. We are releasing a new Phoenix version and have already released a Phoenix live reload plugin. You can either use Phoenix master or downgrade phoenix_live_reload one version. Sorry for the issues. :)
