### ISSUE TITLE
Problems with page reload strategy in LiveView pages embedded via cross-domain iframes

### ISSUE THREAD

**Issue by carlosescri** [phoenixframework/phoenix_live_reload#110]
Hi all!

We are migrating our app to LiveView but the process is so slow we are embedding new features done in LiveView through cross-domain iframes.

Live reload uses an iframe too so I have an iframe inside an iframe inside a page. Both iframes share domain but the domain in the main window is different. Indeed, the iframe sends messages to the parent via `postMessage`.

When live reload tries to reload my iframe it uses `window.top.location.reload` which produces a security error because the browser doesn't allow that.

Shouldn't it try to reload via `window.parent.location.reload`? That should be always be allowed by the browser because there's no domain problem.

Thanks for your time.

**Comment by josevalim** [comment]
See #92, we can change it, but it needs to be controlled via an option. Perhaps an option on live_reload that we embed on the iframe and the iframe can read it.

**Comment by carlosescri** [comment]
I've created a pull request just in case it helps.

**Comment by carlosescri** [comment]
Given that the pull request has been merged I think this can be closed… Thanks!
