### ISSUE TITLE
1.6 support?

### ISSUE THREAD

**Issue by zkat** [phoenixframework/phoenix_live_reload#117]
Hi!

I'm working on upgrading my app from 1.5 to 1.6 and noticed that this project doesn't declare support for 1.6 (yet?)

Should that be fixed? Is there anything in particular stopping it from just doing a version bump?

**Comment by josevalim** [comment]
Hi @zkat! 👋 

This line:

https://github.com/phoenixframework/phoenix_live_reload/blob/master/mix.exs#L43

Means 1.4, 1.5, 1.6 and so on. So we should be all good (and Phoenix should be backwards compatible until 2.0).
