### ISSUE TITLE
Watch for changes outside the project folder

### ISSUE THREAD

**Issue by carlotm** [phoenixframework/phoenix_live_reload#127]
Not sure if this is a bug or not,
is it possible to watch for changes outside the project folder?

I tried configuring `:phoenix_live_reload` like this

```
config :phoenix_live_reload,
  dirs: [
    "../another_project/priv/static",
    ...
  ]
```

but it does not reload.

Thank you

**Comment by josevalim** [comment]
Yes, we set up the watcher inside the project root exclusively, so this won't work. A PR for the docs would be welcome!
