### ISSUE TITLE
Debounce live reload events

### ISSUE THREAD

**Issue by kuon** [phoenixframework/phoenix_live_reload#132]
With inotify, when using a network mount, events are duplicated, and I get a lot of `Live reload:...` everytime I save.

I worked around this issue using `fs_poll` instead of inotify.

Now I just opened https://github.com/aj-foster/phx_copy/issues/2 which is related, and it made me realize it would be cool to also debounce events in live reload itself when using inotify.

Basically, when an event `E0` for file `F` occurs we save the timestamp of that event as `TS0`, we start a 100ms timer (configurable) and every time an event arrive for `F` we ignore it until the end of the timer, at the end of the timer, we do the reload.

**Comment by josevalim** [comment]
There is already such a feature: https://github.com/phoenixframework/phoenix_live_reload/blob/6771687f4652d197f4ace1b63ba6a9560d60932b/lib/phoenix_live_reload/live_reloader.ex#L36

**Comment by kuon** [comment]
My bad, sorry for not finding it. Cheers.

**Comment by kuon** [comment]
I just realized that there is no release with that feature. Do you think you could release `1.3.4` to avoid having to use master? I see that https://github.com/phoenixframework/phoenix_live_reload/issues/130 has been opened.

**Comment by josevalim** [comment]
There was a release last month: https://hex.pm/packages/phoenix_live_reload

**Comment by kuon** [comment]
Ho yes, I didn't see a tag on the repo that's why. I should have read the last commit message.

**Comment by josevalim** [comment]
Tag pushed.
