### ISSUE TITLE
Warning during compilation on Elixir 1.15.x

### ISSUE THREAD

**Issue by crbelaus** [phoenixframework/phoenix_live_reload#137]
When compiling Phoenix Live Reload on Elixir 1.15 or higher I get a warning because it is calling the deprecated [Logger.warn/2](https://hexdocs.pm/logger/Logger.html#warn/2) function.

```
==> phoenix_live_reload
Compiling 4 files (.ex)
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  (phoenix_live_reload 1.4.1) lib/phoenix_live_reload/application.ex:32: Phoenix.LiveReloader.Application.start_link/0

Generated phoenix_live_reload app
```

I was going to open a PR to replace [Logger.warn/2](https://hexdocs.pm/logger/Logger.html#warn/2) with [Logger.warning/2](https://hexdocs.pm/logger/Logger.html#warning/2) but it is only available from Elixir 1.11 and Phoenix Live Reload supports Elixir 1.6, so not sure how to proceed selecting the right function call depending on the Elixir version.

EDIT: I saw that [plug_cowboy was updated to require Elixir 1.11 at least](https://github.com/elixir-plug/plug_cowboy/pull/94). Would that be an acceptable solution here as well?

**Comment by chrismccord** [comment]
Yeah that's fine. Please send a PR!

**Comment by josevalim** [comment]
Yes, we can bump the requirement as long as we release a new minor version.

**Comment by crbelaus** [comment]
Thanks for the feedback. I've just pushed a pull request that fixes the warnings.
