### ISSUE TITLE
A request for publishing a new release

### ISSUE THREAD

**Issue by c4710n** [phoenixframework/phoenix_live_reload#146]
There are some additional improvements since prior version. Among them, commit worth mentioning is:
+ https://github.com/phoenixframework/phoenix_live_reload/pull/138

Maybe, it's time to give it a new release, such as v1.4.2 ?

**Comment by josevalim** [comment]
We will soon, as we work towards v1.5.

**Comment by c4710n** [comment]
Thank you for letting me know about this. 

I will close this issue for now and look forward to version 1.5. ;)
