### ISSUE TITLE
Colour of logs streamed to the web console are not legible in light mode

### ISSUE THREAD

**Issue by DriesCruyskens** [phoenixframework/phoenix_live_reload#155]
The cyan colour of the logs are not legible when using light mode. Is it possible to make the font's colour different for light/dark themes?

<img width="215" alt="Screenshot 2024-03-21 at 10 58 03" src="https://github.com/phoenixframework/phoenix_live_reload/assets/26900172/f244a775-4b40-4958-b940-6e14d61632a8">
<img width="228" alt="Screenshot 2024-03-21 at 10 57 52" src="https://github.com/phoenixframework/phoenix_live_reload/assets/26900172/0b1a9689-4700-4d76-99c9-01ac0244dd5a">

**Comment by ArthurClemens** [comment]
PR #156
