### ISSUE TITLE
Missing live reload functionality on files inside lib. 

### ISSUE THREAD

**Issue by jontonsoup** [phoenixframework/phoenix_live_reload#17]
Is there a way to specify what folders are watched? It seems I'm not getting reloads when I edit my: 

`lib/my_app/i18n/en.ex` file inside of Phoenix.

**Comment by josevalim** [comment]
Nothing in lib is reloaded.
Move it it to web if you want to reload it.


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by jontonsoup** [comment]
@josevalim thanks!

**Comment by jontonsoup** [comment]
@josevalim moving `lib/my_app/i81n/en.ex` to `web/i81n/en/ex` makes it so that my module isn't found anymore. Is there any literature on the load path for phoenix you can point me to?

**Comment by chrismccord** [comment]
@jontonsoup You need to update your `locale` file path references to take the new location into consideration. i.e. `locale "en", Path.join([__DIR__, "../config/locales/en.exs"])` or whererver you have your locales located.

**Comment by sebbean** [comment]
This seems to work for me FYI:
```
config :hello_phoenix, HelloPhoenix.Endpoint,
  reloadable_paths: ["lib"],
  reloadable_compilers: [:elixir]  
```
