### ISSUE TITLE
Reloading CSS causes exponential memory usage

### ISSUE THREAD

**Issue by manveru** [phoenixframework/phoenix_live_reload#23]
There seems to be a bug in the live reloading, here's my `<head>` after saving a CSS file 5 times (without making any changes).

![2015-09-17 16_35_54](https://cloud.githubusercontent.com/assets/3507/9936052/558d81ca-5d5a-11e5-9124-dd95084edeeb.png)

**Comment by josevalim** [comment]
Thank you! Is it because we need to remove the old stylesheet around here? https://github.com/phoenixframework/phoenix_live_reload/blob/master/priv/static/phoenix_live_reload.js#L1

**Comment by manveru** [comment]
well, `link.remove()` is supposed to do that. but it seems like this function is appending two new `<link>` tags for every previous tag.

**Comment by chrismccord** [comment]
I"m trying to recreate without much luck atm

**Comment by chrismccord** [comment]
can you include the entire `head` of your layout here?

**Comment by manveru** [comment]
I suspect it's a combination of a big CSS files and the server being remote, so it could be a race condition?

**Comment by manveru** [comment]
I can give you access to the server if you want, will PM you via slack.

**Comment by Gazler** [comment]
We fixed this over IRC - but for future readers, if you are using vim then the following will fix it:

    set backupcopy=yes

To fix it permanently put that in your vimrc file.

**Comment by chrismccord** [comment]
@manveru fixed on master. Please set vim back to whatever write mode it was doing and verify the fix, then I'll push a new release. Thanks!

**Comment by manveru** [comment]
Sorry, had to do something else first, I couldn't reproduce the bug anymore, so consider it fixed. Thanks for the help!

**Comment by chrismccord** [comment]
1.0.1 has been released, `mix deps.update phoenix_live_reload` and you are all set!
