### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by rauluranga** [phoenixframework/phoenix_live_reload#31]
Hi!
I've created a phoenix project mounted on vagrant, everything works fine except the live reload. 
Is there any place where i can find info about this issue? (live reload works only if i change files inside of the VM).
Thanks!

**Comment by josevalim** [comment]
Yup, that's pretty much a limitation. LiveReload simply won't work in such cases.

**Comment by chrismccord** [comment]
There are known issues with using a VM and shared volumes with mtime/ctime checking, so this isn't something we can fix in this case
