### ISSUE TITLE
Hot Code Reload fails on Arch Linux when directory in path contains a space

### ISSUE THREAD

**Issue by basichash** [phoenixframework/phoenix_live_reload#33]
OS: Arch Linux
Kernel: x86_64 Linux 4.6.2-1-ARCH
Phoenix: v1.1.6
Mix: 1.2.6

Initial app directory contained a space, also inotifytools were not installed. Hot Code Reload was not being triggered when changes were made to /web.
After installing inotifytools, and creating a new app in the same spaced directory, reload was still not being triggered.
After creating a new parent directory and creating a new app, reload was being triggered without issues.

Likely cause: spaced-directory names in the phoenix app path

**Comment by chrismccord** [comment]
> Likely cause: spaced-directory names in the phoenix app path

can you double check by creating a new project with a space in the dir name?

**Comment by basichash** [comment]
Double checked it, when the parent directory contained a space, e.g. 'Parent Dir', hot reload wasn't functioning, but replacing the space with a dash ('Parent-Dir') worked just fine.

**Comment by chrismccord** [comment]
Unfortunately I am unable to replicate this on OS X. It may be an issue specific to inotifytools on certain platforms, but I haven't been able to find any leads on possible solutions. If you find a workaround or more information, please re-open. Thanks!
