### ISSUE TITLE
Live reload on Gettext's *.po files not working when `build_path` is set to `../../_build` (as it would be in an umbrella project)

### ISSUE THREAD

**Issue by oskarkook** [phoenixframework/phoenix_live_reload#37]
Live reload/hot code reload on Gettext's *.po files does not work when `build_path` in `mix.exs` is set to `../../_build` (as it would be in an umbrella project). It works when changing templates etc.

When I remove `build_path` from `mix.exs` or simply change it to `_build`, live reload starts working properly again.

Repo for example:
https://github.com/oskarkook/phoenix-gettext-reload-issue

**Comment by josevalim** [comment]
Thank you. It is an Elixir compiler bug, I am working on it. :)

**Comment by josevalim** [comment]
Solved in v1.3 and master branches.

**Comment by oskarkook** [comment]
Wow, that was fast. Tested master and it works :)
