### ISSUE TITLE
Live-reloading gettext translations doesn't work when starting app from umbrella root

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix_live_reload#40]
It does work but only when started from phoenix app directory: (`cd apps/example_web && iex -S mix phoenix.server`). Example repo: https://github.com/wojtekmach/gettext_umbrella/tree/master/apps

**Comment by chrismccord** [comment]
hmmm can you confirm wether this is specific to gettext or you can recreate for js/css files when running from umbrella root. Thanks!

**Comment by wojtekmach** [comment]
@chrismccord I can confirm it's specific to gettext, when running from umbrella root I verified that reloading templates/js/css worked.

`fs` picked up the change:

```
[debug] Live reload: apps/example_web/priv/gettext/en/LC_MESSAGES/default.po
[info] GET /
[debug] Processing by ExampleWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 369µs
```

just the gettext backend module didn't get recompiled. When I restart `iex` it does get recompiled

**Comment by josevalim** [comment]
Fixed in Phoenix master. :)
