### ISSUE TITLE
Live-reloading gettext translations from other apps in an umbrella

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix_live_reload#41]
Is it possible to live-reload translation changes from other apps within an umbrella?

I'm exploring two different setups:
1. Each app has it's own Gettext module. Example repo: https://github.com/wojtekmach/gettext_umbrella/tree/master/apps
2. There's just one `Translator` app that holds all translation `*.po`, and other apps depend on it. At work, we're leaning towards this setup, but any recommendations are very welcome. Example repo: https://github.com/wojtekmach/gettext_umbrella/tree/translator/apps

Live-reloading doesn't work in either setup.

Might be related to #40

**Comment by josevalim** [comment]
Fixed when #40 was fixed. :)

**Comment by wojtekmach** [comment]
Thank you! ❤️
