### ISSUE TITLE
Do not emit error on missing backend and give hints of how to fix

### ISSUE THREAD

**Issue by NobbZ** [phoenixframework/phoenix_live_reload#42]
A couple of minutes ago, there was a bug report in the visualixir repository because of an errormessage which the user assumed to be from visualixir. The issue in question is koudelka/visualixir#13.

I think it would be easier for new users, if PLR were only emitting a warning instead of an error, and also give a short description (or at least link to one) of what went wrong and how to fix it.

---

I can see arguments though which do say it is an error, since the abscense of a backend renders PLR not working. Even though from a users perspective everything else does work, but filechanges take a moment to catch up.

So if keeping error, please add at least the description mentioned above and a small snippet that the application that everything else _should_ work as expected.

**Comment by chrismccord** [comment]
This is an error produced by the `fs` library, so it's not something we can easily control. We do document on phoenix_live_reload that inotify is required on certain systems. Apart from adding code to check for specific deps per platform, I don't think there is much we can handle here that the docs don't address. I can see how it's frustrating for this case where users think another library is to blame, but I'd prefer to wait to see if this becomes a wider problem. Thanks!
