### ISSUE TITLE
Update to fs 2.12.x

### ISSUE THREAD

**Issue by cliffrowley** [phoenixframework/phoenix_live_reload#44]
Is there a reason that phoenix_live_reload uses the 0.9.x branch of the fs module?  Reason I ask is that the 0.9.x branch doesn't seem to work in Docker properly whereas the 2.12.x branch does.  This is a problem for presumably all watch type tools that need to be installed alongside phoenix_live_reload (https://github.com/lpil/mix-test.watch/issues/61 for example).

Alternatively I'm going to have a peek at the fs module and see if I can spot what the problem is exactly and try to formulate some kind of work around, but it'd be nice to be able to not worry about it :)

**Comment by chrismccord** [comment]
Can you send a PR? There shouldn't be a reason we can't jump on latest stable. Thanks!

**Comment by cliffrowley** [comment]
I can indeed, I'll get on that after a quick break ;-)

**Comment by cliffrowley** [comment]
Oh I noticed @Zorbash has just updated the dependencies https://github.com/phoenixframework/phoenix_live_reload/commit/3dcc7b0a712d0a4da9e16da4de0d0e500906505f

Epic, thanks! :)

**Comment by cliffrowley** [comment]
Wait, I'm an idiot.  This will still need a tag & release, right?
