### ISSUE TITLE
Phoenix fails to compile when using phoenix_live_reload 1.0.7

### ISSUE THREAD

**Issue by rcoedo** [phoenixframework/phoenix_live_reload#45]
I'm trying to use the latest version of the phoenix framework and I'm having some issues. I can't compile the dependencies when using the latest version of the phoenix_live_reload package, everything works if I downgrade to v1.0.6.

This is the error I'm getting:

```
~ mix deps.compile
===> Package <<"pc">> not found. Fetching registry updates and trying again...
===> Plugin pc not available. It will not be used.
===> Package <<"rebar3_hex">> not found. Fetching registry updates and trying again...
===> Plugin rebar3_hex not available. It will not be used.
===> Package <<"pc">> not found. Fetching registry updates and trying again...
===> Plugin pc not available. It will not be used.
===> Package <<"rebar3_hex">> not found. Fetching registry updates and trying again...
===> Plugin rebar3_hex not available. It will not be used.
===> Package <<"pc">> not found. Fetching registry updates and trying again...
===> Plugin pc not available. It will not be used.
===> Package <<"rebar3_hex">> not found. Fetching registry updates and trying again...
===> Plugin rebar3_hex not available. It will not be used.
===> Compiling fs
===> Unable to run pre hooks for 'compile', command 'compile' in namespace 'pc' not found.
** (Mix) Could not compile dependency :fs, "/Users/rcoedo/.mix/rebar3 bare compile --paths "/Users/rcoedo/Workspace/src/github.com/rcoedo/teacher/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile fs", update it with "mix deps.update fs" or clean it with "mix deps.clean fs"
```

Thanks!

**Comment by chrismccord** [comment]
Can you update rebar, clean your build/deps and retry?

    $ rm -rf ~/.cache/rebar3
    $ rm -rf _build
    $ rm -rf deps
    $ mix local.rebar
    $ mix deps.get
    $ mix phoenix.server

**Comment by rcoedo** [comment]
I followed your steps and I still get the same error

**Comment by chrismccord** [comment]
Can you restart your computer and retry as a sanity check?

**Comment by rcoedo** [comment]
I restarted, executed the following:

```
rm -rf ~/.cache/rebar3
rm -rf ~/.cache/rebar
rm -rf ~/.mix/rebar
rm -rf ~/.mix/rebar3
rm -rf _build/
rm -rf deps/
mix local.rebar
mix deps.get
mix phoenix.server
```

Got the same error 😞

**Comment by rcoedo** [comment]
By the way, I'm trying this on a fresh phoenix install following the [installation guide](http://www.phoenixframework.org/docs/installation).

**Comment by josevalim** [comment]
Can you please post your Elixir and Erlang versions?

**Comment by rcoedo** [comment]
@josevalim I've already done it, it's elixir 1.4.0 and erlang 19 😃

**Comment by josevalim** [comment]
Oops, sorry about that. :) I am releasing Elixir v1.4.1 right now because it fixes some Rebar 3 issues. Can you please give it a try in about 10 minutes?

**Comment by rcoedo** [comment]
Sure, I will. thanks a lot!

**Comment by rcoedo** [comment]
Unfortunately I'm still having the same issue

**Comment by josevalim** [comment]
@rcoedo can you please push the app to github?

**Comment by rcoedo** [comment]
@josevalim I uploaded the app [here](https://github.com/rcoedo/test_app). I included the `_build` and `deps`, maybe these can help you in some way.

**Comment by ericmj** [comment]
@rcoedo What does `~/.mix/rebar3 -v` return?

**Comment by rcoedo** [comment]
```
> ~/.mix/rebar3 -v
rebar 3.3.2 on Erlang/OTP 19 Erts 8.2
```

**Comment by josevalim** [comment]
Sorry but I could not reproduce. I am using Elixir v1.4.1, Erlang 18 and the same rebar version. Also using Sierra.

**Comment by rcoedo** [comment]
I just tried replacing erlang 19 with erlang 18 and it didn't work either. I will downgrade to phoenix_live_reload 1.0.6 for now, I hope we can find what causes this problem in the future.

Thanks for your help!

**Comment by chrismccord** [comment]
@rcoedo can you give us some more info if you have a moment?:

What does the following output, with the latest deps that show this error?

    $ DEBUG=1 mix phoenix server

The debug flag should tell us why rebar is failing to fetch the packages. Someone else had this issue just now, and it was fixed only be running `mix local.rebar`, which you've tried. They too are on the same rebar version as you, so the extra debug info would are very helpful. Thanks!

**Comment by rcoedo** [comment]
Sure, [here is the output](https://gist.github.com/rcoedo/343cc6754fab828ec700e9c1e6322f5b).

I hope this helps!

**Comment by chrismccord** [comment]
I have rolled back fs and pushed a new release until we can track this one down. Anyone currently experiencing this can run `mix deps.update phoenix_live_reload`.

**Comment by rcoedo** [comment]
I don't want to be the troll here, but for some reason, the exact same repository that I was testing the other day is working today. It's the the same old 1.0.7 phoenix_live_reload version (I checked it in the mix.lock file).

I have no idea of why or how is this happening 😞

**Comment by josevalim** [comment]
@rcoedo no worries as multiple were reporting this issue. So we would have reverted it anyway (and yes, sometimes the issue would just disappear).

**Comment by inoas** [comment]
> I restarted and executed the following:
> 
> ```
> rm -rf ~/.cache/rebar3
> rm -rf ~/.cache/rebar
> rm -rf ~/.mix/rebar
> rm -rf ~/.mix/rebar3
> rm -rf _build/
> rm -rf deps/
> mix local.rebar
> mix deps.get
> mix phoenix.server
> ```
> 
> Got the same error 😞

This was very helpful when I could not compile old 1.10 apps 
I think there was some conflict around rebar between asdf and mac brew based rebar install.
I got clashes like such:

```
❯ mix deps.compile
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Compiling rebar3_hex
===> Plugin rebar3_hex not available. It will not be used.
=ERROR REPORT==== 23-Dec-2021::15:34:25.648546 ===
Loading of .../deps/p1_utils/_build/default/plugins/rebar3_hex/ebin/rebar3_hex.beam failed: badfile
```
```
  This BEAM file was compiled for a later version of the run-time system than 22.
  To fix this, please recompile this module with an 22 compiler.
  (Use of opcode 169; this emulator supports only up to 168.)
```

**Comment by inoas** [comment]
> Can you update rebar, clean your build/deps and retry?
> 
> ```
> $ rm -rf ~/.cache/rebar3
> $ rm -rf _build
> $ rm -rf deps
> $ mix local.rebar
> $ mix deps.get
> $ mix phoenix.server
> ```

Thank you so much!

**Comment by tsloughter** [comment]
@inoas `p1_utils` should remove `rebar3_hex` from the `plugins` list of their `rebar.config` or `rebar.config.script` in their case. I'd suggest opening an issue or sending a PR to either remove it entirely or move it to `project_plugins` so it isn't fetched when `p1_utils` is used as a dependency.

**Comment by tsloughter** [comment]
Also looks like an old rebar3 since it is building to `deps/p1_utils/_build` and that shouldn't happen anymore, but getting rid of `rebar3_hex` in `p1_utils` is good to do.
