### ISSUE TITLE
Possibility of adding mix.deps get

### ISSUE THREAD

**Issue by liveresume** [phoenixframework/phoenix_live_reload#49]
So besides umbrella projects we can use local folders containing elixir apps as deps with mix.

But this dev cycle requires:
1. Make update to dep project.
2. Run `mix.deps get` in phoenix project.

Would it make sense to add `mix.deps get` to phoenix_live_reload when some special config is present?

- Does this require a full restart of Phoenix, outside the scope of what phoenix_live_reload does?

I will work on this if there are no objections.

**Comment by josevalim** [comment]
You don't need to do add `mix deps.get` if you are using path dependencies. Everything should just work.

**Comment by josevalim** [comment]
And to clarify, `in_umbrella: true` are path dependencies.

**Comment by liveresume** [comment]
Oh I had read somewhere that it was necessary.  And code reload works as well?

**Comment by josevalim** [comment]
Good questions. To clarify:

Phoenix live reload doesn't work across umbrellas (i.e. the thing that automatically detects a change in your assets and then asks the browser to reload the page). It will only notify the browser changes to certain files in your current app.

However, code reloading, which is what runs every time you hit or reload a new page, does work across any path dependency, transparently.

**Comment by liveresume** [comment]
I'm using Vue + webpack in a totally separate project for the frontend so 1 should be ok for me.

Is "code reloading" done by something other than this project?  (it's an elixir/mix thing?)

So all I should have to do is use a reference like:
`{:my_lib, in_umbrella: true, path: "../company-libs/my_lib"}`

**Comment by josevalim** [comment]
Code reloading is only about the Elixir code. If you want to reload the JS
side, then you need to make sure it compiles assets to the priv directory
of your Phoenix application so your changes are picked up.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
As José said, Code reloading is not the same as live reload triggered by changes phoenix_live_reload watched files. When a watched file changes, phoenix_live_reload triggers the browser to reload, which then will issue a new request that is picked up by the Phoenix.CodeReloader, which actually does the elixir code reloading. That will work in the context of umbrella apps, but the live reloader is only configured to trigger refreshes for the `live_reload: [patterns: [...]]` in your endpoint config. You could try adding your relative lib's priv dir to the patterns, but closing as this is not a issue we need to take care of. Thanks!

**Comment by liveresume** [comment]
Checked out the code, I see the difference now.  Thanks for the help!
