### ISSUE TITLE
Do not refresh page with stylesheets, simply reload the css files

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_reload#5]
We could the same as here: https://github.com/brunch/auto-reload-brunch/blob/master/vendor/auto-reload.js#L21-L33

@parkerl, if you would like to implement this feature, please go ahead! :)

**Comment by parkerl** [comment]
On it!

**Comment by parkerl** [comment]
Should the config of what is a css pattern be broken out into a separate key from the rest of the assets? Or should I just make the assumption that anything returned matching `css` is all we care about?

**Comment by parkerl** [comment]
Also just confirming that there are no javascript tests I should be writing against?

**Comment by chrismccord** [comment]
> Or should I just make the assumption that anything returned matching css is all we care about?

This is what I have in mind. We have a couple options. We can pass down the changed file name/path and have the code on the client determine what to do. Or we can just pass down the change event with a file type and the client can react accordingly.

> Also just confirming that there are no javascript tests I should be writing against?

Correct

**Comment by parkerl** [comment]
Thanks @chrismccord 

I guess IMHO the client should be as simple as possible with no spec coverage. I would lean on the server to figure out what to do and then tell the client.  However, I have no problem implementing it either way.

P.S. I just finished listening to you talk about metaprogramming on "Mostly Erlang" and I'm all exited. I think I will do this in a LiveReloading DSL that I will implement in about 17 macros. ;-) In all seriousness though, great stuff! Thanks.

**Comment by chrismccord** [comment]
Heheh thanks! +1 on keeping the client as dumb as possible. We can just pass the file the extname of the changed file. Sound good?

**Comment by parkerl** [comment]
Perfect. I will get this moving then.
