### ISSUE TITLE
Doesn't work with mounted volumes (dockerized)

### ISSUE THREAD

**Issue by dropfen** [phoenixframework/phoenix_live_reload#51]
I tried to setup a dev environment where you could start everything what you need in separate docker containers. And found an interesting behaviour of the live reload package, because it did't recognized file changes when I did the changes on the host. On the other hand, when I changed some file directly inside the container it picked up the changes and reloaded the page. 

But the most strange behaviour showed up, when I then (after the live roload, which was triggered by the change inside the container) changed the file again on the host. It reloaded. I did it again and it reloaded again, but after some seconds, it was the initial state again, when the changes on the host are not triggering this feature at all.

For a quick step in, here is a repo where someone could try it

https://github.com/dropfen/phoenix_live_reload_docker_bug

OR

```
git clone https://github.com/dropfen/phoenix_live_reload_docker_bug && \
cd phoenix_live_reload_docker_bug && \
docker-composer up
```

**Comment by chrismccord** [comment]
This is a known issue and not something we can fix. The issue with mounted volumes is fs events and mtime/ctimes are not propagated properly. You can see similar discussions in other issues but your only options now are to host the code on the same volume it is being served from. Thanks!

**Comment by dropfen** [comment]
Well, thanks for the blazing fast reply 👍
