### ISSUE TITLE
Not working in Freebsd

### ISSUE THREAD

**Issue by ourway** [phoenixframework/phoenix_live_reload#65]
Apparently, freebsd does not have anything like inotify, so Phoenix live reload is not working there.  Inotify is a Linux kernel feature and not supported in BSD.  Any workarounds?

Here the error:

`Couldn't watch modify: No such file or directory`

**Comment by ourway** [comment]
I guess this issue is related to [File_System](https://github.com/falood/file_system), So I am closing it.

**Comment by ourway** [comment]
I guess this issue is related to FileSystem

**Comment by ourway** [comment]
I am still getting this error.  Anyone?

**Comment by josevalim** [comment]
@ourway sorry for the delay here. The solution is to add a new backend to FileSystem that is also capable of handling FreeBSD. One option is to provide integration with fswatch but it is out of scope of phoenix_live_reload to track it. Thanks!
