### ISSUE TITLE
Sometimes the built file will be empty after live reload.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [phoenixframework/phoenix_live_reload#67]
I wrote some codes, they were built succeeded and output into `./priv/static/script/`:
![image](https://user-images.githubusercontent.com/12682063/33940271-4d14cebc-e049-11e7-97d2-50566bbdd0f7.png)

But, if I change my codes and trigger the `live-hot`, sometimes the copied file in `_build/dev/lib/my_app_path/priv/static/` would be cleared:
![image](https://user-images.githubusercontent.com/12682063/33940327-809784dc-e049-11e7-9346-6ce570470f3e.png)

This doesn't happened every times, but I think it maybe due to the size of the file was too large and this plugin reload the file early.

***
I took a try, every time I clear the terminal manual and trigger reload, then record if the file in `_build` directory was cleared:

First, start the server, the file was correctly and page looks well:
![image](https://user-images.githubusercontent.com/12682063/33940701-02c2bc6e-e04b-11e7-8bde-5d081d4ee9ff.png)

Clear the terminal and trigger a reload:
![image](https://user-images.githubusercontent.com/12682063/33940742-29c927e4-e04b-11e7-9f2d-c475250765ea.png)

Repeat last step sometimes until the problem happend:
![image](https://user-images.githubusercontent.com/12682063/33940813-73ffe942-e04b-11e7-9a31-62d0d47ab1a4.png)

***
After  compared those too case, we can see the different, while the logger looks like those, everything works well:
![image](https://user-images.githubusercontent.com/12682063/33940910-c7a54fc4-e04b-11e7-8179-97bee8a02cdd.png)

And if the log looks like those, the finally built file would be cleared:
![image](https://user-images.githubusercontent.com/12682063/33940938-e7b3d4ca-e04b-11e7-9e5f-e1421463fa06.png)

***
I hope that this problem could be fixed as soon as possible, it really interfere my work, thank you.

**Comment by zhengxiaoyao0716** [comment]
Maybe you can take a try, the project ispublic, here the repository: [honeycomb-adventure](https://github.com/zhengxiaoyao0716/honeycomb-adventure) .
And here my environment:
![image](https://user-images.githubusercontent.com/12682063/33941396-70c9c4ee-e04d-11e7-8050-5655572fbb91.png)
 Windows 10 Version 1703, Enterprise edition.

Hoped this information can make some help.

**Comment by josevalim** [comment]
Thank you @zhengxiaoyao0716! It seems this issue is specific to Windows. Since we can't properly use symlinks on Windows, we need to copy the files and something is happening when we copy them.

Pinging @OvermindDL1 in case he has any ideas what may be happening.

**Comment by zhengxiaoyao0716** [comment]
Well, I'm glad that I could help you. Since this problem may caused by `symlinks` and only happened on Windows, I'll try to working on other system for the moment.

**Comment by OvermindDL1** [comment]
I thought a message was added at load time that warned you exactly of this and how to fix it as well, wasn't it?

**Comment by chrismccord** [comment]
> The issue is that... phoenix is too fast ...

:D In all seriousness I don't think we can help this one on our end, but maybe we can include docs somewhere for windows to recommend running as admin?

**Comment by OvermindDL1** [comment]
> :D In all seriousness I don't think we can help this one on our end

Lol, more that the beam is too fast because it does not listen for the windows even that says a flush is complete, and even then if an anti-virus exists then it will lock the file before it could be re-opened anyway, thus still causing the same issue...  ^.^;

> but maybe we can include docs somewhere for windows to recommend running as admin?

I thought it was already documented when a person loads a phoenix server in dev mode on windows, it should print a good sized paragraph talking about exactly this issue and what to do to work around it.  I *know* I last saw it when I last ran the server on windows (thankfully I finally convinced my job to migrate the servers fully to linux, red hat but eh).

**Comment by OvermindDL1** [comment]
Ah, yes indeed it is still there:

https://github.com/phoenixframework/phoenix/blob/8dbb2609dc933b367b8463a4cee62d2f3cde0f8d/lib/phoenix/code_reloader/server.ex#L37

And:

https://github.com/phoenixframework/phoenix/blob/8dbb2609dc933b367b8463a4cee62d2f3cde0f8d/lib/phoenix/code_reloader/server.ex#L81

**Comment by chrismccord** [comment]
ah, beautiful. Thanks!

**Comment by zhengxiaoyao0716** [comment]
@OvermindDL1 Thanks, I found the message, it is just in the third screenshots of the first floor, but I didn't realize it at first that this was the reason of this problem.

**Comment by zhengxiaoyao0716** [comment]
@OvermindDL1 As the message guide, I tried to run phx.server as `Administrator`, and found the `priv` folder in `_build` now is a symbol link, and seems no problems.
![image](https://user-images.githubusercontent.com/12682063/33971947-294cfe24-e0b6-11e7-994a-b31403d56533.png)

**Comment by zhengxiaoyao0716** [comment]
I have a small idea, the only thing we need is to create some symbol links as `Administrator` for those folders.
We don't need to create them each times at the `phx.server` task. we can provide another task to allow user create those symlinks as `Administrator`, then each time that `phx.server` start, check those symlinks and if they are not exist, give a tip to users that they need manual execute the task as `Administrator` to generate those symlinks.
Although this way may not the better and user have to take an extra step, I think this is the most simple patch,.

**Comment by zhengxiaoyao0716** [comment]
Umm, perhaps we have a easier choise, just change the message like `you need to run this task as Administrator at least once time`, if user did this and the symbol links already exist, hide the message.

**Comment by OvermindDL1** [comment]
> if user did this and the symbol links already exist, hide the message.

Hmm, a check to see if the symlink already exists and points to the correct location might indeed be a good quality-of-life workaround, and only be a line or two of code to implement (if the BEAM has a command to query that information, I'm not actually sure, never used it...).  You should PR it?  :-)

**Comment by OvermindDL1** [comment]
> it is just in the third screenshots of the first floor, but I didn't realize it at first that this was the reason of this problem.

Also, heh, it is, I missed it too.  I could have sworn it was red when I had it.

**Comment by zhengxiaoyao0716** [comment]
@OvermindDL1 That is my PR , I tested those code on my windows system locally and they works well, but maybe we need more test on other systems.

In addition, I tried some terminals I can found on my Win10, powershell, cmd, mingw. But none of them can render color with [warn] logger. In my VSCode debug console, the message starts with `warning` is red, but [warn] logs still can't.

**Comment by OvermindDL1** [comment]
> In addition, I tried some terminals I can found on my Win10, powershell, cmd, mingw. But none of them can render color with [warn] logger. In my VSCode debug console, the message starts with warning is red, but [warn] logs still can't.

For note, none of what you listed are terminals but rather are shells.  The terminal you were probably using was 'command'.  I tend to use conemu as the terminal myself though.
