### ISSUE TITLE
Phoenix is locked in a loop when a file is reloaded on Windows

### ISSUE THREAD

**Issue by kojoru** [phoenixframework/phoenix_live_reload#7]
Steps to reproduce:
1. Install Phoenix as in tutorial on Windows
2. Launch `mix phoenix.server`
2. Open http://localhost:4000 in a web browser
3. Change a template

Result: a web page is reloaded indefinitely. 
Expected result: a web page is reloaded once 

I don't always see the behavior but I see it most of the time. The reason seems to be that template editing triggers the rebuild of files like `_build\dev\lib\<projectname>\priv\static\js` which match happily against the default regexp `priv/static/.*(js|css|png|jpeg|jpg|gif)$` which cause rebuild again.

As a result something as crude as setting `live_reload` config to 
```
patterns: [
      ~r{^.*(?!.*_build.*).*priv/static/.*(js|css|png|jpeg|jpg|gif)$},
      ~r{^.*(?!.*_build.*).*web/views/.*(ex)$},
      ~r{^.*(?!.*_build.*).*web/templates/.*(eex)$}
    ]
```

works. But that doesn't seem to be needed on other patforms. Why?

**Comment by josevalim** [comment]
Two questions: are you on windows? And which elixir version?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by kojoru** [comment]
Yes, on Windows, as mentioned in the title. Edited the post to make it more clear.

Elixir is on version 1.0.4, phoenix is 0.11

**Comment by josevalim** [comment]
Thank you! I completely missed it on the title. :) I know exactly why this
happens. On windows we can't symlink, so we copy files triggering the event
multiple times. Your work around is great, we should fix live reload though
to just ignore everything from _build.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by kojoru** [comment]
I could probably do the PR to ignore `_build` myself, is it ok? 

However I'm not sure if it is better done by hardcoding `_build` or by defining a generic "and not matches some oter regexp" algorithm, what do you think?

Besides there are currently no tests for `channel.ex`, is there any specific reason for it?

**Comment by josevalim** [comment]
A PR would be great. We don't have tests because Phoenix doesn't have
channel testing conveniences yet. We could support an :ignore regex
option that by default is ~r"_build/".

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
Ping.

**Comment by chrismccord** [comment]
I can take care of this today

**Comment by chrismccord** [comment]
@kojoru This should be fixed with the default `:patterns`. Please test on master and report back and I'll push a new release to hex:

```elixir
{:phoenix_live_reload, github: "phoenixframework/phoenix_live_reload"},
...
```

**Comment by lstor** [comment]
This resolves phoenixframework/phoenix/issues/805, at least =)
