### ISSUE TITLE
CSS reload not working in iframe

### ISSUE THREAD

**Issue by jakub-zawislak** [phoenixframework/phoenix_live_reload#71]
I have an app which has an iframe that comes from the same app. When I change CSS of iframe's site, then nothing happens, CSS in iframe is not reloaded. 

Changes in HTML/JS of iframe's site works fine, the whole page is always reloaded. It's obvious because it always reloads page regardless of which file was modified. So the problem is with that complex CSS reloading. 

Anyway, it would be nice to have option to force page refresh when CSS is changed. What if JS reads something from CSS on init and then CSS is reloaded without JS reloading?

**Comment by josevalim** [comment]
> . What if JS reads something from CSS on init and then CSS is reloaded without JS reloading?

What do you mean?

**Comment by jakub-zawislak** [comment]
For example, you have a script that on page load assigns to a variable some [computed style](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) and uses it later. Of course it's value depends on CSS file. Then CSS is reloaded. Then JS could have old invalid value. 

I've never had such case. I'm sometimes using that getComputedStyle, but always when user click on something etc. so it's value depends on actual state of page, not the initial one.

Another example - someone could use CSS variables, which is not supported by every browser yet. For such browsers there are polyfills written in JS. And again, JS will not handle that new reloaded CSS.

I know, these are extremely rare cases

**Comment by josevalim** [comment]
@jakub-zawislak oh, I see. In any way, I think a pull request to force reload would be welcome.
