### ISSUE TITLE
Choosing desired Backend

### ISSUE THREAD

**Issue by likal** [phoenixframework/phoenix_live_reload#78]
FileSystem allows to use custom backend. So instead of default ":fs_notify" (inotify-tools) I wish to use :fs_poll which doesn't need extra dependencies.

"start_link" has hard coded opts so there is no way to pass "backend: :fs_poll".

It would be good to alter this setting from "config.exs" or even "dev.exs" in Phoenix app.

**Comment by josevalim** [comment]
Can you please send a pull request? Thank you! :D

**Comment by chrismccord** [comment]
We should reference it from the `config :my_app, MyApp.Endpoint, live_reload: [backend: ...]` keyspace

**Comment by josevalim** [comment]
@chrismccord IIRC that is not possible today because we start only a single file system watcher. We would need to rewrite how this part of the system works in order to support a watcher per backend. So a global config is fine for me.

**Comment by chrismccord** [comment]
Ah, you are right. Given this is only dev, a global config can work for now 👍🏻

**Comment by likal** [comment]
Just prepared small change to set backend directly from `config/config.exs`
