### ISSUE TITLE
Question: `window.top` vs. `window.parent`

### ISSUE THREAD

**Issue by aj-foster** [phoenixframework/phoenix_live_reload#81]
In the JavaScript portion of this project, the `pageStrategy` scheme causes a reload using `window.top.location.reload()` ([see here](https://github.com/phoenixframework/phoenix_live_reload/blob/master/priv/static/phoenix_live_reload.js#L44)). This makes sense, as the JavaScript itself is running inside of an `iframe`.

However, I'm curious if there was a specific motivation for using `window.top` rather than `window.parent`. We load the Phoenix application in another `iframe` (for good reasons I can share if necessary); thus the `window.top` escapes one too many levels and reloads more than necessary.

Ours is definitely a special use-case, and we're prepared to create & maintain a fork of this project to support it. However, it would be nice to know if there are any edge cases or other considerations we may be missing.

Thank you for your time!

/cc @parkerl as the committer of the relevant line

**Comment by josevalim** [comment]
Parent would be fine for me, we could give it a try. In the worst scenario
we make it customizable.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by parkerl** [comment]
I seem to recall that the reload code itself is injected via an iframe. This might cause issues with “window.parent”? Honestly can’t remember exactly.

**Comment by aj-foster** [comment]
I feared something like that might be true. Our tests with `window.parent` have been successful so far, but we have not been comprehensive in our browser selection.

We’re happy to maintain a fork with this change for our needs. If time allows, I will attempt to do further testing. In the meantime, feel free to close out this issue — and thank you all for your time!

**Comment by chrismccord** [comment]
If you are able to test on IE please let us know how it goes and we can get this change in place. Thanks!
