### ISSUE TITLE
mix.exs specifies 'or ~> 1.4' which does not match '1.4.0-rc.0'

### ISSUE THREAD

**Issue by aspett** [phoenixframework/phoenix_live_reload#86]
mix.exs specifies 'or ~> 1.4' which does not match '1.4.0-rc.0', as seen when trying to `mix deps.get`

```
Failed to use "phoenix" (version 1.4.0-rc.0) because
  phoenix_live_reload (version 1.1.7) requires ~> 1.0 or ~> 1.2 or ~> 1.3 or ~> 1.4 *
  mix.exs specifies ~> 1.4.0-rc.0
```

**Comment by chrismccord** [comment]
I literally *just* pushed 1.1.7 which fixes this! :D Thank you!!!

**Comment by aspett** [comment]
I think this is still an issue @chrismccord :P 

`or ~> 1.4` doesn't match `~> 1.4.0-rc`

**Comment by aspett** [comment]
https://github.com/phoenixframework/phoenix_live_reload/blob/master/mix.exs#L39

**Comment by chrismccord** [comment]
Yeah are right, sorry :)

**Comment by chrismccord** [comment]
I have updated the upgrade guides to instruct `{:phoenix, "~> 1.4.0-rc", override: true}`. Thank you!

**Comment by aspett** [comment]
No, no! Thank you :)

**Comment by ericmj** [comment]
We are planning on fixing this in hex: https://github.com/hexpm/hex/issues/613
