### ISSUE TITLE
Phoenix close the connection if the request need more time than normal

### ISSUE THREAD

**Issue by bingoabs** [phoenixframework/phoenix_live_reload#89]
Hi, I came cross a issue that the `Phoenix Application` will close the connection after about 60s.

I have a `nginx server` before the `Application`, I found the `nginx error log` show `upstream prematurely closed connection while reading response header from upstream`.

Check the `Application log`, I found the `Application` just close the request without any log!
I think someone can find the behavior just use `:timer.sleep(70_000) ` in any handler.

I think the endpoint is responsible for this. So I check the [endpoint](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html) and find the `:http - the configuration for the HTTP server. Currently uses Cowboy and accepts all options as defined by Plug.Cowboy. Defaults to false`.
I found I should config the `cowboy`, the [cowboy server](https://ninenines.eu/docs/en/cowboy/2.5/manual/cowboy_http/) has some params, I think the `idle_timeout` or 'inactivity_timeout` is more important for this issue.

So I config the `http: [protocol_options: [idle_timeout: 300_000, inactivity_timeout: 300_000]],` and solve this problem.

My question is why the server not emit the error message ? I think it is hard to add the missing config if we do not have any obviously information.

**Comment by josevalim** [comment]
Closing this as mentioned, thanks for the report!

**Comment by bingoabs** [comment]
@josevalim  I am sorry. And thanks a lot for your reply
