### ISSUE TITLE
CSS change triggers full page reload

### ISSUE THREAD

**Issue by topaxi** [phoenixframework/phoenix_live_reload#94]
The README states that CSS file changes should not trigger a full page refresh, but changing the default CSS in a phoenix application does indeed trigger one.

This seems to be caused indirectly by using webpack, as changing the CSS file also changes the JavaScript file.

**Comment by josevalim** [comment]
If so, it is not really a bug in LiveReload but rather in the webpack configuration. Ideally, if the JS does not change, then webpack should not write a new file to disk. Could you please send a PR to our builtin webpack configuration to make sure that/s the case? Thank you!
