### ISSUE TITLE
release 1.2.1? (with fs_poll config)

### ISSUE THREAD

**Issue by petermm** [phoenixframework/phoenix_live_reload#95]
hate to ask.. but can we have 1.2.1 from master (which includes the fs_poll config https://github.com/phoenixframework/phoenix_live_reload/pull/90) 

Doing a beginner tutorial - and it's quite the killer/distraction/wrong to setup a github dep from the get go..

fwiw cpu goes from 70% to 1% when the fs_polling is limited to relevant dirs..

**Comment by josevalim** [comment]
Done! :D
