### ISSUE TITLE
[error] an exception was raised:  ** (ArgumentError) unknown registry: nil

### ISSUE THREAD

**Issue by leductam** [phoenixframework/phoenix_live_reload#98]
I got this logs when run Win 10, please review.
`Last message: {:join, Phoenix.Channel.Server}
State: {%{}, {#PID<0.472.0>, #Reference<0.315827230.2814640129.256588>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveReloader.Channel, channel_pid: nil, endpoint: DemoWeb.Endpoint, handler: Phoenix.LiveReloader.Socket, id: nil, join_ref: "108", joined: false, private: %{}, pubsub_server: nil, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "phoenix:live_reload", transport: :websocket, transport_pid: #PID<0.472.0>}}
[error] an exception was raised:
    ** (ArgumentError) unknown registry: nil
        (elixir 1.10.1) lib/registry.ex:1239: Registry.info!/1
        (elixir 1.10.1) lib/registry.ex:920: Registry.register/3
        (phoenix_pubsub 2.0.0-dev) lib/phoenix/pubsub.ex:117: Phoenix.PubSub.subscribe/3
        (phoenix 1.5.0-dev) lib/phoenix/channel/server.ex:401: Phoenix.Channel.Server.init_join/3
        (phoenix 1.5.0-dev) lib/phoenix/channel/server.ex:375: Phoenix.Channel.Server.channel_join/4
        (phoenix 1.5.0-dev) lib/phoenix/channel/server.ex:299: Phoenix.Channel.Server.handle_info/2
        (stdlib 3.11) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib 3.11) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib 3.11) proc_lib.erl:249: :proc_lib.init_p_do_apply/3`

Done to remove `pubsub: [name: Rumbl.PubSub, adapter: Phoenix.PubSub.PG2]` from config and added 
`children = [
      # Start the endpoint when the application starts
      DemoWeb.Endpoint,
      {Phoenix.PubSub, [name: Demo.PubSub, adapter: Phoenix.PubSub.PG2]}
    ]`

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error? Thank you!

**Comment by leductam** [comment]
Actually, I've just created the Demo Phoenix Application with "mix phx.new demo --no-ecto", with specified deps:
elixir 1.10.1
phoenix 1.5.0-dev
phoenix_pubsub 2.0.0-dev
phoenix_live_reload 1.2.1

And followed the guide to remove pubsub from config and add the child Phoenix.PubSub. That all and got the error message when accessed to http://localhost:4000/

**Comment by josevalim** [comment]
Did you add `pubsub_server: Rumbl.PubSub` to your configuration when you remove the `:pubsub` one?

**Comment by josevalim** [comment]
Also, make sure that the name in your supervision tree matches the name you declare on pubsub_server. I have improved Phoenix master to raise a better error message in case like yours, thanks!

**Comment by leductam** [comment]
Yes, I passed the step to add pubsub_server, I did it and the error message disappeared.
It is normal now. I saw the message at browser ["3","3","phoenix:live_reload","phx_join",{}], ["3","3","phoenix:live_reload","phx_reply",{"response":{},"status":"ok"}], and also try to changed some code and reloading is fine.

Thanks Jose.
