### ISSUE TITLE
~r"lib/liveview_web/{live,views}/.*(ex)$" not triggering live reload

### ISSUE THREAD

**Issue by sfusato** [phoenixframework/phoenix_live_reload#99]
This is the default setting in `dev.ex` for a new Phoenix project:
```      
~r"lib/liveview_web/{live,views}/.*(ex)$",
```
This won't trigger a live-reload for changes done in either `/live` or `/views` directories. I'm on Manjaro Linux. Can't test on anything else.

Changing the syntax a bit to the following works:
```      
~r"lib/liveview_web/(live|views)/.*(ex)$",
```

**Comment by josevalim** [comment]
This has been fixed in Phoenix master.
